# NeON build file (http://github.com/c4s4/neon)

extends: golang
default: [fmt, check, test]
expose:  [fmt, check, test, release]
configuration: '~/.neon/github.yml'
# GITHUB_TOKEN: 'abcdefghijklmnopqrstuvwxyz0123456789'

targets:

  test:
    doc: Run an integration test
    steps:
    - print: 'Running test in threads...'
    - try:
      - threads: 2
        steps:
        - $: 'go run single.go 12345 sleep 1 2> /dev/null'
      - 'failure = true'
      catch:
      - 'failure = false'
    - if: failure
      then:
      - throw: 'Integration test failed'
      else:
      - print: 'Integration test success'
